version: 1.1
kind: operation
name: build-spacy-streamlit
params:
  destination:
    connection: "docker-connection"
    value: polyaxon-examples:spacy-streamlit-demo
  context:
    value: "{{ globals.artifacts_path }}/spacy-streamlit-polyaxon-demo"
runPatch:
  init:
    - git:
        url: "https://github.com/avivkri/spacy-streamlit-polyaxon-demo"
hubRef: kaniko
